language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --env=prod

after_success:
  - node fix-sw.js
  - firebase deploy --token $FIREBASE_DEPLOY_KEY

notifications:
  email:
    on_failure: $EMAIL
    on_success: $EMAIL